# Tip: https://ci.appveyor.com/tools/validate-yaml
version: '{branch}-{build}'
branches:
  only:
  - appveyor
init:
  # Gather some basic build environment details.
  - rem set
  - dir "%ProgramFiles(x86)%\Microsoft Visual Studio *" /b /o
  - dir "%ProgramFiles%\Microsoft SDKs\Windows" /b /o
  - dir "%SystemDrive%\Qt\5.*" /b /o
environment:
  VSVER: 14.0
  matrix:
    - QTDIR: C:\Qt\5.4\msvc2013_opengl
    - QTDIR: C:\Qt\5.4\msvc2013_64_opengl
    - QTDIR: C:\Qt\5.5\mingw492_32
install:
  # Setup the build toolchains.
  - '%QTDIR%\bin\qtenv2.bat'
  - qmake -v
  - if %QTDIR:_64=%==%QTDIR% ( set ARCH=x86 ) else set ARCH=x64
  - if %QTDIR:msvc=%==%QTDIR% g++ --version
  - if %QTDIR:msvc=%==%QTDIR% set make=mingw32-make.exe
  - if %QTDIR:msvc=%==%QTDIR% %make% --version
  - if not %QTDIR:msvc=%==%QTDIR% call "%ProgramFiles(x86)%\Microsoft Visual Studio %VSVER%\VC\vcvarsall.bat" %ARCH%
  - if not %QTDIR:msvc=%==%QTDIR% set make=nmake.exe
  - if not %QTDIR:msvc=%==%QTDIR% %make% /? > nul
before_build:
  # Prepare the out-of-source build directory.
  - mkdir %APPVEYOR_BUILD_FOLDER%-build
  - cd %APPVEYOR_BUILD_FOLDER%-build
  - qmake -Wall -Wlogic -Wparser CONFIG+=debug_and_release %APPVEYOR_BUILD_FOLDER%
build_script:
  - '%make% all'
test_script:
  # @todo output using Qt's -xunitxml option
  - '%make% check'
# @todo after_test upload results
