version: '{branch}-{build}'

environment:
  matrix:
    - QTDIR: C:\Qt\5.6\mingw49_32
    - QTDIR: C:\Qt\5.6\msvc2013
    - QTDIR: C:\Qt\5.6\msvc2013_64
    - QTDIR: C:\Qt\5.6\msvc2015
    - QTDIR: C:\Qt\5.6\msvc2015_64
    - QTDIR: C:\Qt\5.7\mingw53_32
    - QTDIR: C:\Qt\5.7\msvc2015
    - QTDIR: C:\Qt\5.9\mingw53_32
    - QTDIR: C:\Qt\5.9\msvc2013_64
    - QTDIR: C:\Qt\5.9\msvc2015
    - QTDIR: C:\Qt\5.9\msvc2015_64
    - QTDIR: C:\Qt\5.10\mingw53_32
    - QTDIR: C:\Qt\5.10\msvc2013_64
    - QTDIR: C:\Qt\5.10\msvc2015
    - QTDIR: C:\Qt\5.10\msvc2015_64
    - QTDIR: C:\Qt\5.11\mingw53_32
    - QTDIR: C:\Qt\5.11\msvc2015
    - QTDIR: C:\Qt\5.11\msvc2015_64
    - QTDIR: C:\Qt\5.12\mingw73_32
    - QTDIR: C:\Qt\5.12\mingw73_64
    - QTDIR: C:\Qt\5.12\msvc2015_64
    - QTDIR: C:\Qt\5.13\mingw73_32
    - QTDIR: C:\Qt\5.13\mingw73_64
    - QTDIR: C:\Qt\5.13\msvc2015_64

install:
  #- C:\cygwin\bin\find C:\Qt -maxdepth 2 -type d
  - cmake --version
  - set PATH
  - if %QTDIR:msvc=%==%QTDIR% set "PATH="
  - set "PATH="
  - set PATH
  - '%QTDIR%\bin\qtenv2.bat'
  - set PATH
  - if %QTDIR:_64=%==%QTDIR% ( set MSVC_ARCH=x86 ) else set MSVC_ARCH=x64
  - if %QTDIR:msvc=%==%QTDIR% g++ --version
  - if %QTDIR:msvc=%==%QTDIR% set make=mingw32-make.exe
  - if %QTDIR:msvc=%==%QTDIR% %make% --version
  - if not %QTDIR:msvc2013=%==%QTDIR% call "%ProgramFiles(x86)%\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %ARCH%
  - if not %QTDIR:msvc2015=%==%QTDIR% call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %ARCH%
  - if not %QTDIR:mingw=%==%QTDIR% set "CMAKE_GENERATOR=MinGW Makefiles"
  - if not %QTDIR:msvc=%==%QTDIR% set "CMAKE_GENERATOR=NMake Makefiles"
  - if not %QTDIR:msvc=%==%QTDIR% set make=nmake.exe
  - if not %QTDIR:msvc=%==%QTDIR% %make% /? > nul
  - set CMAKE

before_build:
  # Prepare the out-of-source build directory.
  - mkdir %APPVEYOR_BUILD_FOLDER%-build
  - cmake -G %CMAKE_GENERATOR% -S %APPVEYOR_BUILD_FOLDER% -B %APPVEYOR_BUILD_FOLDER%-build

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%-build
  - dir
  - '%make%'

after_build:
  # Add a link to the build output within the source directory. This is needed because AppVeyor does
  # not support extracting artifacts from out-of-source build directories. See 'artifacts' below.
  # @todo build artifacts are all different now...
  #- mklink %APPVEYOR_BUILD_FOLDER%\qtaws.dll %APPVEYOR_BUILD_FOLDER%-build\%CONFIGURATION%\qtaws.dll

test_script:
  # @todo output using Qt's -xunitxml option
  - if not %CONFIGURATION%==debug %make% check TESTARGS=-silent

# @todo after_test upload results

#artifacts:
#  - path: qtaws.dll

#notifications:
#  - provider: Webhook
#    url: https://webhooks.gitter.im/e/db2b6ec088084f138e57
